spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: My9@passw0rd
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
